### ISSUE TITLE
Block device mapping should be flexible.

### ISSUE THREAD

**Issue by jschwartzentruber** [MozillaSecurity/laniakea#21]
The `Laniakea.images` dictionary assumes one block device per machine and it is named `/dev/sda1`. This is not a universal name, and prevents laniakea from launching AMIs with other requirements. For example the official AMIs for CoreOS use `/dev/xvda1`.

Currently, launching a spot request for CoreOS-stable AMI with laniakea gives the following:

    State: failed: Either snapshot ID or volume size must be provided for: /dev/sda1
    Status: bad-parameters: Your Spot request failed due to bad parameters.

**Comment by posidron** [comment]
Fixed by: https://github.com/MozillaSecurity/laniakea/commit/61f8999f8946c2d1d30f67f9eab9b317999e195a
